# bash-pipes
# Autogenerated from man page /usr/share/man/man6/bash-pipes.6.gz
complete -c bash-pipes -s p -d 'Number of pipes.  (default is 1)'
complete -c bash-pipes -s t -d 'Determines the type of pipes to be drawn.  Multiple arguments can be used'
complete -c bash-pipes -s c -d 'Colors of pipes.  Multiple arguments can be used'
complete -c bash-pipes -s f -d 'Frame rate.  (default is 75)'
complete -c bash-pipes -s s -d 'Probability of straight fitting.  (default is 13)'
complete -c bash-pipes -s r -d 'Resets the drawing after [LIMIT] characters'
complete -c bash-pipes -s R -d 'Randomize starting position and direction'
complete -c bash-pipes -s B -d 'No bold effect'
complete -c bash-pipes -s C -d 'No color'
complete -c bash-pipes -s K -d 'No change of colors and types when hitting screen edges'
complete -c bash-pipes -s h -d 'Displays a help message'
complete -c bash-pipes -s v -d 'Prints the version number'

