# cxxmatrix
# Autogenerated from man page /usr/share/man/man1/cxxmatrix.1.gz
complete -c cxxmatrix -l help -d 'Show help'
complete -c cxxmatrix -s m -l message -d 'Add a message for \'banner\' scene'
complete -c cxxmatrix -s s -l scene -d 'Add scenes'
complete -c cxxmatrix -s c -l color -d 'Set color'
complete -c cxxmatrix -l colorspace -d 'Set colorspace'
complete -c cxxmatrix -l frame-rate -d 'Set the frame rate per second.  A positive number less than or equal to 1000'
complete -c cxxmatrix -l error-rate -d 'Set the factor for the rate of character changes.  A non-negative number'
complete -c cxxmatrix -l diffuse -d 'Turn on the background-color effect (default)'
complete -c cxxmatrix -l no-diffuse -d 'Turn off the background-color effect'
complete -c cxxmatrix -l twinkle -d 'Turn on the twinkling effect (default)'
complete -c cxxmatrix -l no-twinkle -d 'Turn off the twinkling effect'
complete -c cxxmatrix -l preserve-background -d 'Preserve terminal background'
complete -c cxxmatrix -l no-preserve-background -d 'Not preserve terminal background (default)'
complete -c cxxmatrix -l rain-density -d 'Set the factor for the density of rain drops.  A positive number'

