# boxes
# Autogenerated from man page /usr/share/man/man1/boxes.1.gz
complete -c boxes -s a -d 'Alignment/positioning of text inside box'
complete -c boxes -s c -d 'Command line design definition for simple cases'
complete -c boxes -s d -d 'Design selection'
complete -c boxes -s e -d 'Override line terminator.   eol can be  CR,  LF, or  CRLF'
complete -c boxes -s f -d 'Use alternate config file'
complete -c boxes -l help -d 'TQ  -h Print usage information'
complete -c boxes -s i -d 'Indentation mode'
complete -c boxes -s k -d 'Kill leading/trailing blank lines on removal'
complete -c boxes -s l -d '(ell) List designs'
complete -c boxes -s m -d 'Mend box'
complete -c boxes -s n -d 'Character encoding'
complete -c boxes -s p -d Padding
complete -c boxes -s q -d 'Query designs by tag'
complete -c boxes -s r -d 'Remove an existing box.  Which design to use is detected automatically'
complete -c boxes -s s -d 'Box size'
complete -c boxes -s t -d 'Tab handling'
complete -c boxes -s h -d 'Print usage information'
complete -c boxes -s v -d 'Print out current version number'

