# optirun
# Autogenerated from man page /usr/share/man/man1/optirun.1.gz
complete -c optirun -l failsafe -d 'run a program even if the nvidia card is unavailable'
complete -c optirun -l no-failsafe -d 'do not run a program if the nvidia card is unavailable'
complete -c optirun -l no-xorg -d 'do not start secondary X server (implies -b none)'
complete -c optirun -s b -l bridge -d 'acceleration/displaying bridge to use'
complete -c optirun -s c -l vgl-compress -d 'image compression or transport to use with VirtualGL'
complete -c optirun -l vgl-options -d 'a space-separated list of command options to be passed to vglrun'
complete -c optirun -l primus-ldpath -d 'a colon-separated list of paths which are searched for the primus libGL. so'
complete -c optirun -s q -l quiet -l silent -d 'supresses all logging messages'
complete -c optirun -s v -l verbose -d 'increase the verbosity level of log messages'
complete -c optirun -l debug -d 'show all logging messsages by setting the verbosity level to the maximum'
complete -c optirun -s C -l config -d 'retrieve settings for Bumblebee from FILE'
complete -c optirun -s d -l display -d 'find the Bumblebee X server on VDISPLAY'
complete -c optirun -s l -l ldpath -d 'libraries like libGL. so are searched in PATH (useful for the nvidia driver)'
complete -c optirun -s s -l socket -d 'use FILENAME for communication with the daemon'
complete -c optirun -s h -l help -d 'display this help and exit'
complete -c optirun -l version -d 'output version information and exit EXAMPLES'

