# slurm
# Autogenerated from man page /usr/share/man/man1/slurm.1.gz
complete -c slurm -s h -d 'Print usage information and quit'
complete -c slurm -s H -d 'add hostname to title'
complete -c slurm -s c -d 'start slurm with classic/combined graph'
complete -c slurm -s s -d 'start slurm in split graph mode'
complete -c slurm -s l -d 'start slurm in large split graph mode'
complete -c slurm -s z -d 'virtually zero traffic counters instead of showing values stored in kernel'
complete -c slurm -s d -d 'delay between screen updates in milliseconds (1000 = once per second)'
complete -c slurm -s i -d 'select interface to monitor (required) El KEYS slurm supports several differe…'

