# pipes_orig
# Autogenerated from man page /usr/share/man/man6/pipes_orig.sh.6.gz
complete -c pipes_orig -s p -d 'Number of pipes.  (default is 1)'
complete -c pipes_orig -s t -d 'Determines the type of pipes to be drawn.  Multiple arguments can be used'
complete -c pipes_orig -s c -d 'Colors of pipes.  Multiple arguments can be used'
complete -c pipes_orig -s f -d 'Frame rate.  (default is 75)'
complete -c pipes_orig -s s -d 'Probability of straight fitting.  (default is 13)'
complete -c pipes_orig -s r -d 'Resets the drawing after [LIMIT] characters'
complete -c pipes_orig -s R -d 'Randomize starting position and direction'
complete -c pipes_orig -s B -d 'No bold effect'
complete -c pipes_orig -s C -d 'No color'
complete -c pipes_orig -s K -d 'No change of colors and types when hitting screen edges'
complete -c pipes_orig -s h -d 'Displays a help message'
complete -c pipes_orig -s v -d 'Prints the version number'

