# sl
# Autogenerated from man page /usr/share/man/man1/sl.1.gz
complete -c sl -s a -d 'An accident is occurring.  People cry for help'
complete -c sl -s c -d 'C51 appears instead of D51'
complete -c sl -s d -d 'Disco mode.  Alternate colors during animation'
complete -c sl -s e -d 'Escape.  Allow interrupt by Ctrl+C'
complete -c sl -s F -d 'It flies like the galaxy express 999'
complete -c sl -s G -d 'It\'s French like Oscar'
complete -c sl -o '<number' -d 'Specify the number of cars like `sl -5`'
complete -c sl -s l -d 'Little version'
complete -c sl -s w -d 'Windy day.  Locomotive moves faster'
complete -c sl -s v -d 'Prints the version and last updated'

