const SlideTypes = {
  WELCOME: "WELCOME",
  NEW_VS_RETURNING: "NEW_VS_RETURNING",
  USER_TYPE: "USER_TYPE",
  TABLE_TUTORIAL: "TABLE_TUTORIAL",
  ACCOUNT_SELECTION: "ACCOUNT_SELECTION",
  SUMMARY: "SUMMARY",
  ACTIVATE_LICENSE: "ACTIVATE_LICENSE",
};

const TableCaptureExperience = {
  NEW_USER: "NEW_USER",
  RETURNING_USER: "RETURNING_USER",
};
