# alsaconf
# Autogenerated from man page /run/current-system/sw/share/man/man8/alsaconf.8.gz
complete -c alsaconf -s c -l config -d 'Specify the module config file'
complete -c alsaconf -s d -l devmode -d 'Set the device mode for the ALSA devices (default = 0666)'
complete -c alsaconf -s g -l gid -d 'Set the gid for the ALSA devices (default = 0)'
complete -c alsaconf -s h -l help -d 'Displays this help text'
complete -c alsaconf -s L -l log -d 'Logging on the given file.   The log is appended to the file'
complete -c alsaconf -s l -l legacy -d 'Check only for legacy non-isapnp cards'
complete -c alsaconf -s m -l modinfo -d 'Read module descriptions instead of reading a card database'
complete -c alsaconf -s P -l listprobe -d 'List the supported legacy card modules'
complete -c alsaconf -s p -l probe -d 'Probe a legacy non-isapnp card and print module options'
complete -c alsaconf -s r -l strict -d 'Set strict device mode (equiv.  with -g 17 -d 0660)'
complete -c alsaconf -s s -l sound-wav-file -d 'Use the specified wav file as a test sound'
complete -c alsaconf -s u -l uid -d 'Set the uid for the ALSA devices (default = 0)'

