# axfer
# Autogenerated from man page /run/current-system/sw/share/man/man1/axfer.1.gz
complete -c axfer -s l -d ','
complete -c axfer -l list-devices -d ','
complete -c axfer -s L -d ','
complete -c axfer -l list-pcms -d 'are acknowledged as list subcommand'

