# chvt
# Autogenerated from man page /run/current-system/sw/share/man/man1/chvt.1.gz
complete -c chvt -s V -l version -d 'print program version and exit'
complete -c chvt -s h -l help -d 'show this text and exit'

