# nixos-option
# Autogenerated from man page /run/current-system/sw/share/man/man8/nixos-option.8.gz
complete -c nixos-option -s r -d 'Print all the values at or below the specified path recursively'
complete -c nixos-option -s I -d 'This option is passed to the underlying nix-instantiate 1 invocation'

