# nvidia-smi
# Autogenerated from man page /run/current-system/sw/share/man/man1/nvidia-smi.1.gz
complete -c nvidia-smi -l mode -d 'This mode is the default clock locking mode and provides the highest possible…'

