# okular
# Autogenerated from man page /run/current-system/sw/share/man/man1/okular.1.gz
complete -c okular -s p -l page -d 'Open a given page in the document'
complete -c okular -l presentation -d 'Start the document in presentation mode'
complete -c okular -l print -d 'Start with print dialog'
complete -c okular -l print-and-exit -d 'Start with print dialog and exit after printing'
complete -c okular -l unique -d 'Unique instance control'
complete -c okular -l noraise -d 'Allows to prevent Okular window raising after the start'
complete -c okular -l find -d 'Find a string on the text'
complete -c okular -l editor-cmd -d 'Sets the external editor command'

