# uxterm
# Autogenerated from man page /run/current-system/sw/share/man/man1/uxterm.1.gz
complete -c uxterm -o class -d and
complete -c uxterm -o u8 -d 'options should not be specified because they are used by the wrapper'

