# xinput
# Autogenerated from man page /run/current-system/sw/share/man/man1/xinput.1.gz
complete -c xinput -l version -d 'Test if the X Input extension is available and return the version number of t…'

